### ISSUE TITLE
Update package documentation

### ISSUE THREAD

**Issue by vvasuki** [astrorigin/pyswisseph#11]
http://pythonhosted.org/pyswisseph/ seems outdated. It would be a good idea to update..

**Comment by astrorigin** [comment]
That site not under my responsibility. Sorry.

**Comment by vvasuki** [comment]
Is there some way of automatically generating such documentation? For example using sphinx on readthedocs.io ? That'd be very helpful.

**Comment by astrorigin** [comment]
https://docs.python.org/3/library/pydoc.html
http://epydoc.sourceforge.net/

**Comment by vvasuki** [comment]
Ah - if you are already able to generate such documentation, you could host it online - all you need to do is put it under the docs folder of this repository, and follow the [instructions here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch). Then, users will be able to refer to  astrorigin.github.io/pyswisseph for the latest docs..

**Comment by astrorigin** [comment]
https://astrorigin.com/pyswisseph/pydoc/index.html

**Comment by vvasuki** [comment]
It exists! I feel mildly abashed for directly googling pyswisseph and getting the wrong documentation page from https://pypi.python.org/pypi/pyswisseph ; and not instead finding the doc page linked in the bottom of https://astrorigin.com/pyswisseph/ linked from README.md .

Could you obviate it by:
- Linking to https://astrorigin.com/pyswisseph/pydoc/index.html from README.md
- and fixing the link at https://pypi.python.org/pypi/pyswisseph (perhaps releasing the latest update at pypi while at it) ?
