### ISSUE TITLE
installing error Anaconda3 + python 3.6 (windows 10)

### ISSUE THREAD

**Issue by anzber** [astrorigin/pyswisseph#12]
Can someone help to solve this problem:

pip install pyswisseph

Collecting pyswisseph
  Using cached pyswisseph-2.00.00-2.tar.bz2
Building wheels for collected packages: pyswisseph
  Running setup.py bdist_wheel for pyswisseph ... error
  Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\A\\AppData\\Local\\Temp\\pip-build-s59wqh7f\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\A\AppData\Local\Temp\tmpf9uxxvzqpip-wheel- --python-tag cp36:
  Searching system libswe...
  Found pkg-config
  Using internal libswe
  C:\Anaconda3\lib\site-packages\setuptools\dist.py:351: UserWarning: Normalizing '2.00.00-2' to '2.0.0.post2'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  building 'swisseph' extension
  creating build
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\libswe
  creating build\temp.win-amd64-3.6\Release\swephelp
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c pyswisseph.c -o build\temp.win-amd64-3.6\Release\pyswisseph.o -std=gnu99
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swecl.c -o build\temp.win-amd64-3.6\Release\libswe\swecl.o -std=gnu99
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swedate.c -o build\temp.win-amd64-3.6\Release\libswe\swedate.o -std=gnu99
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swehel.c -o build\temp.win-amd64-3.6\Release\libswe\swehel.o -std=gnu99
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swehouse.c -o build\temp.win-amd64-3.6\Release\libswe\swehouse.o -std=gnu99
  C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swejpl.c -o build\temp.win-amd64-3.6\Release\libswe\swejpl.o -std=gnu99
  libswe/swejpl.c:78:19: error: conflicting types for 'off_t'
     typedef __int64 off_t;
                     ^
  In file included from C:/Anaconda3/Library/mingw-w64/x86_64-w64-mingw32/include/io.h:169:0,
                   from libswe/sweodef.h:86,
                   from libswe/swephexp.h:83,
                   from libswe/swejpl.c:71:
  C:/Anaconda3/Library/mingw-w64/x86_64-w64-mingw32/include/_mingw_off_t.h:26:17: note: previous declaration of 'off_t' was here
   typedef off32_t off_t;
                   ^
  error: command 'C:\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyswisseph
  Running setup.py clean for pyswisseph
Failed to build pyswisseph
Installing collected packages: pyswisseph
  Running setup.py install for pyswisseph ... error
    Complete output from command C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\A\\AppData\\Local\\Temp\\pip-build-s59wqh7f\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\A\AppData\Local\Temp\pip-b96hno6d-record\install-record.txt --single-version-externally-managed --compile:
    Searching system libswe...
    Found pkg-config
    Using internal libswe
    C:\Anaconda3\lib\site-packages\setuptools\dist.py:351: UserWarning: Normalizing '2.00.00-2' to '2.0.0.post2'
      normalized_version,
    running install
    running build
    running build_ext
    building 'swisseph' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\libswe
    creating build\temp.win-amd64-3.6\Release\swephelp
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c pyswisseph.c -o build\temp.win-amd64-3.6\Release\pyswisseph.o -std=gnu99
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swecl.c -o build\temp.win-amd64-3.6\Release\libswe\swecl.o -std=gnu99
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swedate.c -o build\temp.win-amd64-3.6\Release\libswe\swedate.o -std=gnu99
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swehel.c -o build\temp.win-amd64-3.6\Release\libswe\swehel.o -std=gnu99
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swehouse.c -o build\temp.win-amd64-3.6\Release\libswe\swehouse.o -std=gnu99
    C:\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ilibswe -Iswephelp -IC:\Anaconda3\include -IC:\Anaconda3\include -c libswe/swejpl.c -o build\temp.win-amd64-3.6\Release\libswe\swejpl.o -std=gnu99
    libswe/swejpl.c:78:19: error: conflicting types for 'off_t'
       typedef __int64 off_t;
                       ^
    In file included from C:/Anaconda3/Library/mingw-w64/x86_64-w64-mingw32/include/io.h:169:0,
                     from libswe/sweodef.h:86,
                     from libswe/swephexp.h:83,
                     from libswe/swejpl.c:71:
    C:/Anaconda3/Library/mingw-w64/x86_64-w64-mingw32/include/_mingw_off_t.h:26:17: note: previous declaration of 'off_t' was here
     typedef off32_t off_t;
                     ^
    error: command 'C:\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\A\\AppData\\Local\\Temp\\pip-build-s59wqh7f\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\A\AppData\Local\Temp\pip-b96hno6d-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\A\AppData\Local\Temp\pip-build-s59wqh7f\pyswisseph\

**Comment by aloistr** [comment]
Try this:
Edit swejpl.c and change
                                                                                                             
#if MSDOS                                                                                                    
  typedef __int64 off_t;                                                                                     
  #define FSEEK _fseeki64                                                                                    
  #define FTELL _ftelli64                                                                                    
#else                                                                                                        
  #define FSEEK fseeko                                                                                       
  #define FTELL ftello                                                                                       
#endif      

Into
                                                                                                             
#if MSDOS                                                                                                    
  typedef __int64 off_t64;                                                                                  
  #define FSEEK _fseeki64                                                                                    
  #define FTELL _ftelli64                                                                                    
#else          
  typedef off_t off_t64 ;                          // new                                                                   
  #define FSEEK fseeko                                                                                       
  #define FTELL ftello                                                                                       
#endif      

Further down, replace every occurrence of off_t into off_t64

**Comment by mnsarma** [comment]
you can use unofficial windows binary wheel from *https://www.lfd.uci.edu/~gohlke/pythonlibs/*.
use wheel based on your windows/python version. it works good. that's how i got it working in my windows 10.
solution : *pip install pyswisseph‑2.5.1.post0‑cp37‑cp37m‑win_amd64.whl*

**Comment by Tjorriemorrie** [comment]
I also could not install it (using pipenv):
```
  error: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\BIN\\\\x86_amd64\\\\link.exe' failed with exit status 1120",
```

This does not seem to work for me:
```
$ pipenv run pip install pyswisseph-2.5.1.post0-cp37-cp37m-win_amd64.whl
pyswisseph-2.5.1.post0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by mnsarma** [comment]
@Tjorriemorrie  
Check the version of python you have in Anaconda and also if your system is 32/64 bit. depending on that , try the respective wheel.

**Comment by Tjorriemorrie** [comment]
It is still failing though
```
$ pipenv install --skip-lock pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl
Installing pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl…
Adding pyswisseph to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile…
An error occurred while installing flatlib! Will try again.
An error occurred while installing ./pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl! Will try again.
  ================================ 6/6 - 00:00:13
Installing initially failed dependencies…
     ================================ 2/2 - 00:00:01
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Requirement already up-to-date: flatlib in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages (0.2.1)', 'Requirement already satisfied, skipping upgrade: pyswisseph>=2.00.00-2 in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages (from flatlib) (2.5.1.post0)']
[pipenv.exceptions.InstallError]: ['No metadata found in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages', "Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '~\\\\.virtualenvs\\\\trading-leksrkgh\\\\lib\\\\site-packages\\\\pyswisseph-2.5.1.post0.dist-info\\\\METADATA'"]
ERROR: ERROR: Package installation failed...
```

**Comment by Tjorriemorrie** [comment]
It is still failing though
```
$ pipenv install --skip-lock pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl
Installing pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl…
Adding pyswisseph to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile…
An error occurred while installing flatlib! Will try again.
An error occurred while installing ./pyswisseph-2.5.1.post0-cp36-cp36m-win_amd64.whl! Will try again.
  ================================ 6/6 - 00:00:13
Installing initially failed dependencies…
     ================================ 2/2 - 00:00:01
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Requirement already up-to-date: flatlib in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages (0.2.1)', 'Requirement already satisfied, skipping upgrade: pyswisseph>=2.00.00-2 in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages (from flatlib) (2.5.1.post0)']
[pipenv.exceptions.InstallError]: ['No metadata found in ~\\.virtualenvs\\trading-leksrkgh\\lib\\site-packages', "Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '~\\\\.virtualenvs\\\\trading-leksrkgh\\\\lib\\\\site-packages\\\\pyswisseph-2.5.1.post0.dist-info\\\\METADATA'"]
ERROR: ERROR: Package installation failed...
```

**Comment by mnsarma** [comment]
line 4 says installation succeeded right . once try the example program
_>>> import swisseph as swe
>>> swe.set_ephe_path('/usr/share/ephe') # set path to ephemeris files
>>> now = swe.julday(2007,3,3) # get Julian day number
>>> res = swe.lun_eclipse_when(now) # find next lunar eclipse (from now on)
>>> ecltime = swe.revjul(res[1][0]) # get date UTC
>>> ecltime
(2007, 3, 3, 23.347975596785545) # this is output 
>>> jd = swe.julday(2008,3,21)
>>> swe.calc_ut(jd, swe.AST_OFFSET+13681)[0] # asteroid Monty Python
0.098474291148756998  # this is output 
>>> help(swe)_

**Comment by astrorigin** [comment]
Package from PyPI is obsolete and must be updated.

**Comment by astrorigin** [comment]
Package on PyPI has been updated. Hopefully builds on Windows with no problems...
