### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by wayspurrchen** [astrorigin/pyswisseph#15]
Hi! Thanks so much for your work on this project. I noticed that the documentation at https://astrorigin.com/pyswisseph has been down for a couple of weeks, which I had been using actively prior. Would it be possible to have this brought up? If not, would you be able to supply the documentation artefact as a .zip? I'd also be happy to donate some money if server costs are an issue.

**Comment by mnsarma** [comment]
use the documentation in the below link:
*https://pythonhosted.org/pyswisseph/swisseph-module.html*

**Comment by astrorigin** [comment]
You can extract all documentation with setup tools (or epydoc, etc). Web site should be up again soon.
