### ISSUE TITLE
failed building wheel for pyswisseph in windows

### ISSUE THREAD

**Issue by mnsarma** [astrorigin/pyswisseph#16]
Hi, when i run the command 'pip install pyswisseph' i get the following error. please help me with a solution.
C:\WINDOWS\system32>pip install pyswisseph
Collecting pyswisseph
  Using cached https://files.pythonhosted.org/packages/09/27/10ad652fa0e07fc89890142a6f900725e26cf02a24d8fd724015e08707b5/pyswisseph-2.00.00-2.tar.bz2
Building wheels for collected packages: pyswisseph
  Running setup.py bdist_wheel for pyswisseph ... error
  Complete output from command c:\users\narayana\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Narayana\\AppData\\Local\\Temp\\pip-install-swqa6n0z\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Narayana\AppData\Local\Temp\pip-wheel-mycn_b8b --python-tag cp37:
  Searching system libswe...
  pkg-config not found
  Using internal libswe
  c:\users\narayana\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py:398: UserWarning: Normalizing '2.00.00-2' to '2.0.0.post2'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  building 'swisseph' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\libswe
  creating build\temp.win-amd64-3.7\Release\swephelp
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibswe -Iswephelp -Ic:\users\narayana\appdata\local\programs\python\python37\include -Ic:\users\narayana\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" /Tcpyswisseph.c /Fobuild\temp.win-amd64-3.7\Release\pyswisseph.obj -std=gnu99
  cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
  pyswisseph.c
  c:\users\narayana\appdata\local\programs\python\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyswisseph
  Running setup.py clean for pyswisseph
Failed to build pyswisseph
Installing collected packages: pyswisseph
  Running setup.py install for pyswisseph ... error
    Complete output from command c:\users\narayana\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Narayana\\AppData\\Local\\Temp\\pip-install-swqa6n0z\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Narayana\AppData\Local\Temp\pip-record-7pf8hpc5\install-record.txt --single-version-externally-managed --compile:
    Searching system libswe...
    pkg-config not found
    Using internal libswe
    c:\users\narayana\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py:398: UserWarning: Normalizing '2.00.00-2' to '2.0.0.post2'
      normalized_version,
    running install
    running build
    running build_ext
    building 'swisseph' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\libswe
    creating build\temp.win-amd64-3.7\Release\swephelp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibswe -Iswephelp -Ic:\users\narayana\appdata\local\programs\python\python37\include -Ic:\users\narayana\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" /Tcpyswisseph.c /Fobuild\temp.win-amd64-3.7\Release\pyswisseph.obj -std=gnu99
    cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
    pyswisseph.c
    c:\users\narayana\appdata\local\programs\python\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\narayana\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Narayana\\AppData\\Local\\Temp\\pip-install-swqa6n0z\\pyswisseph\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Narayana\AppData\Local\Temp\pip-record-7pf8hpc5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Narayana\AppData\Local\Temp\pip-install-swqa6n0z\pyswisseph\

C:\WINDOWS\system32>

**Comment by mnsarma** [comment]
found solution:
use unofficial windows binary wheel from 'https://www.lfd.uci.edu/~gohlke/pythonlibs/'. use wheel based on your windows/python version.
solution : pip install pyswisseph‑2.5.1.post0‑cp37‑cp37m‑win_amd64.whl

**Comment by molnaredom** [comment]
I faced with the same issue on Linux.
Do you have any solution for this case?

**Comment by sakg-dev** [comment]
So this error persists even now, here's how I solved in linux:
- `apt install python3.13-dev`
- `pip install pyswisseph --no-cache-dir --no-binary=pyswisseph`

These cmds will create wheel instead of using prebuilt one
