### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by canabadyweb** [astrorigin/pyswisseph#20]
When I issue the below statement in shell:
==================================

$ python3 -m jyotisha.panchangam.scripts.write_daily_panchangam_tex Chennai 13:05:24  80:16:12 'Asia/Calcutta' 2019 devanagari

It throws' error as below:
===================
DEBUG: 2019-08-20 17:39:43,678 {common.py:868}: {'DataSource': <class 'sanskrit_data.schema.common.DataSource'>, 'JsonObject': <class 's
anskrit_data.schema.common.JsonObject'>, 'JsonObjectNode': <class 'sanskrit_data.schema.common.JsonObjectNode'>, 'NamedEntity': <class 'sanskrit_data.schema.common.NamedEntity'>, 'SchemaError': <class 'jsonschema.exceptions.SchemaError'>, 'ScriptRendering': <class 'sanskrit_data.schema.common.ScriptRendering'>, 'Target': <class 'sanskrit_data.schema.common.Target'>, 'TargetValidationError': <class 'sanskrit_data.schema.common.TargetValidationError'>, 'Text': <class 'sanskrit_data.schema.common.Text'>, 'UllekhanamJsonObject': <class 'sanskrit_data.schema.common.UllekhanamJsonObject'>, 'ValidationError': <class 'jsonschema.exceptions.ValidationError'>}
DEBUG: 2019-08-20 17:39:43,997 {temporal.py:483}: {'DataSource': <class 'sanskrit_data.schema.common.DataSource'>, 'JsonObject': <class
'sanskrit_data.schema.common.JsonObject'>, 'JsonObjectNode': <class 'sanskrit_data.schema.common.JsonObjectNode'>, 'NamedEntity': <class 'sanskrit_data.schema.common.NamedEntity'>, 'SchemaError': <class 'jsonschema.exceptions.SchemaError'>, 'ScriptRendering': <class 'sanskrit_data.schema.common.ScriptRendering'>, 'Target': <class 'sanskrit_data.schema.common.Target'>, 'TargetValidationError': <class 'sanskrit_data.schema.common.TargetValidationError'>, 'Text': <class 'sanskrit_data.schema.common.Text'>, 'UllekhanamJsonObject': <class 'sanskrit_data.schema.common.UllekhanamJsonObject'>, 'ValidationError': <class 'jsonschema.exceptions.ValidationError'>, 'Time': <class 'jyotisha.panchangam.temporal.Time'>}
DEBUG: 2019-08-20 17:39:43,997 {spatio_temporal.py:1505}: {'DataSource': <class 'sanskrit_data.schema.common.DataSource'>, 'JsonObject': <class 'sanskrit_data.schema.common.JsonObject'>, 'JsonObjectNode': <class 'sanskrit_data.schema.common.JsonObjectNode'>, 'NamedEntity': <class 'sanskrit_data.schema.common.NamedEntity'>, 'SchemaError': <class 'jsonschema.exceptions.SchemaError'>, 'ScriptRendering': <class 'sanskrit_data.schema.common.ScriptRendering'>, 'Target': <class 'sanskrit_data.schema.common.Target'>, 'TargetValidationError': <class 'sanskrit_data.schema.common.TargetValidationError'>, 'Text': <class 'sanskrit_data.schema.common.Text'>, 'UllekhanamJsonObject': <class 'sanskrit_data.schema.common.UllekhanamJsonObject'>, 'ValidationError': <class 'jsonschema.exceptions.ValidationError'>, 'Time': <class 'jyotisha.panchangam.temporal.Time'>, 'City': <class 'jyotisha.panchangam.spatio_temporal.City'>, 'Panchangam': <class 'jyotisha.panchangam.spatio_temporal.Panchangam'>, 'datetime': <class 'datetime.datetime'>}
Loaded pre-computed panchangam from ../precomputed/Chennai-2019.json.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/canabady/.local/lib/python3.6/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_tex.py", line 66, in <module>
    main()
  File "/home/canabady/.local/lib/python3.6/site-packages/jyotisha/panchangam/scripts/write_daily_panchangam_tex.py", line 56, in main
    panchangam.computeFestivals()
  File "/home/canabady/.local/lib/python3.6/site-packages/jyotisha/panchangam/spatio_temporal.py", line 658, in computeFestivals
    self.jd_sunrise[d - 2] + 4, args=(
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by astrorigin** [comment]
Unable to fix your bugs.
