### ISSUE TITLE
Consider building and releasing wheels with pypi releases.

### ISSUE THREAD

**Issue by ShadowJonathan** [astrorigin/pyswisseph#24]
With setuptools it is possible to build and release python wheels alongside normal "source" releases, currently what is being uploaded to pypi are those source-based releases, and clients have to build+compile the library at install time.

Wheels speeds up this process by doing the compiling first before annotating the wheel file with the required restrictions (python version, OS, CPU architecture) for it to be able to run on another version.

I'm suggesting to build wheels for difficult-to-compile systems like windows (`win32`, `win_amd64`), macos, and Linux (`manylinux`) on python versions 3.5 through 3.8 in an array formation.

I'm suggesting using [cibuildwheel](https://pypi.org/project/cibuildwheel/), which works with Travis CI, which is free to use.

Building wheels can speedup install times and make sure users don't have to install build/compile/link tools on their machines for them to use this library (or any that depend on it).

**Comment by ShadowJonathan** [comment]
May I ask why this was closed without comment?

**Comment by ShadowJonathan** [comment]
May I ask why this was closed without comment?
@astrorigin

**Comment by ShadowJonathan** [comment]
Sidenote, I see that it is also possible to initiate such a build process directly from GitHub actions, github's own CI system; https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions

**Comment by astrorigin** [comment]
You have been assigned this "issue". The public is now waiting for you.

You can fork this project directly from Github, too.

**Comment by ShadowJonathan** [comment]
Thank you, I asked that question to clear up some confusion.

Tomorrow (as of may 3rd) I'm indeed planning to fork and mess around with cibuildwheel in my own fork, before submitting a pull request.

**Comment by astrorigin** [comment]
Merged into branch cibuildwheel. Closing issue. Thanks.
