### ISSUE TITLE
Issues in calculating the nakshatra

### ISSUE THREAD

**Issue by dalalns** [astrorigin/pyswisseph#30]
could you please check why i am getting wrong nakshatra while using this library.
I have create the question and posted on stackoverflow at below location.
https://stackoverflow.com/questions/62200954/using-pyswisseph-getting-wrong-output-while-finding-nakshatra

**Comment by astrorigin** [comment]
No idea, but if you're using the development version of pyswisseph, you could try this:

```
import swisseph as swe
from swisseph import contrib as swh

swe.set_ephe_path('/usr/share/swisseph')

res, flg = swe.calc_ut(swh.jdnow(), swe.MOON)
nak, pada = swh.long2nakshatra(res[0])
print('Nakshatra = %d, pada = %d' % (nak, pada))
```

The contrib module previously was private-hidden in the swe module, so just put an underscore before the function.
