### ISSUE TITLE
heliacal_ut(..)

### ISSUE THREAD

**Issue by mnsarma** [astrorigin/pyswisseph#33]
Hi, 

I'm using the pyswisseph for ephemeris, it's working fine. 
however, i'm trying to get the heliacal rising of stars. It doesn't seem to work at all. 

code: 
    star = 'Sirius'
    dp_star_data  = swe.heliacal_ut(jd, [80, 16, 0], [0.0, 0.0, 0.0, 0.0], 
                                 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
                                  star, swe.HELIACAL_RISING, 
                                  swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH )

This is never returning values. whenever i use this function and run the code, the project hangs and doesn't seem to recover until  I reset. Is there any fix for this or am I using it wrong. 

Thanks,
Narayana

**Comment by amitb132** [comment]
Hi mnsarma,

I agree with you. I have tried it numerous times too but it isn't working. Please do update the solution here if you find any. I will too.

**Comment by mnsarma** [comment]
Hi, 

Still no luck. Whenever I use the function for stars the whole software hangs without any result.
Any solution to this?

**Comment by astrorigin** [comment]
I cannot reproduce that bug. Do you have more information about your system, and a complete script to replicate the bug?

**Comment by mnsarma** [comment]
Hi,

I'm using the pyswisseph for ephemeris, it's working fine.
However, I'm trying to get the heliacal rising of stars & planets. It
doesn't seem to work at all.

code:
star = 'Sirius'
dp_star_data = swe.heliacal_ut(jd, [80, 16, 0], [0.0, 0.0, 0.0, 0.0],
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
star, swe.HELIACAL_RISING,
swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH )

also for planets::

venus_data = swe.heliacal_ut(pJd, place, 0, 0, swe.SUKRA,
swe.MORNING_FIRST, swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH)

This is never returning values. Whenever I use this function and run the
code, the project hangs and doesn't seem to recover until I reset. Is there
any fix for this or am I using it wrong? All others functions are working
fine for me.

I basically want to get the star and planetary phenomenon like
first rise and set, longitudes of stars for a particular jd.

Thanks,
Narayana

**Comment by astrorigin** [comment]
Thanks for copy-pasta, That is not answering my previous questions (system info, software version, complete script).

By the way, `swe.SUKRA` actually is not in the `swisseph` namespace. What about that?!

Clone this repository, recompile the latest version, please.

**Comment by amitb132** [comment]
This worked for me:

`lon = 72.8593441  # longitude of Mumbai as example
lat = 19.0601638  # latitude of Mumbai as example
place = (lon, lat, 0)
atm = (0,0,0,0) # atmospheric conditions.
obs = (36,1,0,0,0,0) # observer description. 36 here is the age of the observer.
jd = swe.julday(1985,12,25,22,10)
print(jd)
venus_data = swe.heliacal_ut(jd, place, atm, obs, 'venus',
swe.HELIACAL_RISING, swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH)
print(venus_data) # returns a tuple of start visibility, optimum visibility and end of visibility.`

**Comment by amitb132** [comment]
This worked for me:

`lon = 72.8593441  # longitude of Mumbai
lat = 19.0601638  # latitude of Mumbai
place = (lon, lat, 0)
atm = (0,0,0,0) # atmospheric conditions.
obs = (36,1,0,0,0,0) # observer description. 36 here is the age of the observer.
jd = swe.julday(1985,12,25,22,10)
print(jd)
venus_data = swe.heliacal_ut(jd, place,atm, obs, 'venus',
swe.HELIACAL_RISING, swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH)
print(venus_data) # returns a tuple of start visibility, optimum visibility and end of visibility.`

**Comment by amitb132** [comment]
this worked for me:
`lon = 72.8593441  # longitude of Mumbai`
`lat = 19.0601638  # latitude of Mumbai`
`place = (lon, lat, 0)`
`atm = (0,0,0,0) # atmospheric conditions.`
`obs = (36,1,0,0,0,0) # observer description. 36 here is the age of the observer.`
`jd = swe.julday(1985,12,25,22,10)`
`print(jd)`
`venus_data = swe.heliacal_ut(jd, place,atm, obs, 'venus',`
`swe.HELIACAL_RISING, swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH)`
`print(venus_data) # returns a tuple of start visibility, optimum visibility and end of visibility.`

**Comment by mnsarma** [comment]
> this worked for me: `lon = 72.8593441 # longitude of Mumbai` `lat = 19.0601638 # latitude of Mumbai` `place = (lon, lat, 0)` `atm = (0,0,0,0) # atmospheric conditions.` `obs = (36,1,0,0,0,0) # observer description. 36 here is the age of the observer.` `jd = swe.julday(1985,12,25,22,10)` `print(jd)` `venus_data = swe.heliacal_ut(jd, place,atm, obs, 'venus',` `swe.HELIACAL_RISING, swe.HELFLAG_HIGH_PRECISION + swe.FLG_SWIEPH)` `print(venus_data) # returns a tuple of start visibility, optimum visibility and end of visibility.`

which version of swiss ephemeris are you using?

**Comment by amitb132** [comment]
I'm using version 2.08
