### ISSUE TITLE
swe.fix_stars_ut not finding sefstars.txt

### ISSUE THREAD

**Issue by vvasuki** [astrorigin/pyswisseph#35]
Code:

`            (_, lat, _, _, _, _) = swe.fixstar_ut("Spica", jd)`

output:

`E           swisseph.Error: SwissEph file 'sefstars.txt' not found in PATH '/usr/share/swisseph:/usr/local/share/swisseph/'
`

**Comment by astrorigin** [comment]
Until you provide code to repeat the bug,I will assume you forgot to previously call swe.set_ephe_path(...)

Thanks.

**Comment by vvasuki** [comment]
I am not calling `swe.set_ephe_path` - thanks for telling me about it.

But why is sefstars.txt not distributed with this package? I just get the following files, and am unable to point set_ephe_path to sefstars. (One shouldn't need to download it separately.)
```
    /usr/lib/python3.8/site-packages/pyswisseph-2.8.0.post2.dist-info/*
    /usr/lib/python3.8/site-packages/swisseph.cpython-38-x86_64-linux-gnu.so
```

Commands  used for installation:
 
`sudo pip3 install git+https://github.com/astrorigin/pyswisseph@master -U`  
Alternatively: `sudo pip3 install pyswisseph`

**Comment by astrorigin** [comment]
Sorry, it's been like that since forever. I know it's far from ideal. A separate application to download needed files should be created eventually. See https://github.com/astrorigin/swisseph/blob/master/contrib/mirror_ephedir.sh

**Comment by vvasuki** [comment]
Our downstream package successfully distributes lots of data files (now including sefstars.txt) via manifest file  - https://github.com/sanskrit-coders/jyotisha/blob/master/MANIFEST.in . Couldn't pyswisseph do the same? That will be far better and clearer.
