### ISSUE TITLE
cannot install pyswisseph==2.00.00-2  in win10

### ISSUE THREAD

**Issue by zgpnuaa** [astrorigin/pyswisseph#36]
In win10, i want install pyswisseph==2.00.00-2 because a  package only support this version, but there are some errors:

pyswisseph.obj : warning LNK4197: export 'PyInit_swisseph' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.7\Release\swisseph.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\swisseph.cp37-win_amd64.exp
swhgeo.obj : error LNK2001: unresolved external symbol strtok_r
build\lib.win-amd64-3.7\swisseph.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

**Comment by astrorigin** [comment]
With Windows, I suggest that you prepare the compilation with CMake.
See https://gist.github.com/ifmihai/9fae789ef1ed2fcbedc5ace7cb1d3797

**Comment by astrorigin** [comment]
A step-by-step recipe for compilation on Windows should be written (sphinx documentation, chapter installation).
