### ISSUE TITLE
Eventual failure to access Chiron data

### ISSUE THREAD

**Issue by apollograce** [astrorigin/pyswisseph#37]
I have a test application that needs to compute the positions of planets (and dwarf planets), the moon, and Chiron over many different dates, which it does rapidly in succession from a series of server API calls.

They're all working except my sole asteroid, Chiron - and Chiron works for a while, but then fails. So maybe the first thousand iterated calls work fine, but then I start getting the error "SwissEph file 'seas_18.se1' not found in PATH". It's right there in the path, along with sepl_18.se1 and semo_18.se1. I'm using a "Singleton" class to make sure we access it through only a single thread. The failure is in the call to calc_ut, with various julian days from the 20th century, and the point ID set to 15 (chiron).

Any thoughts on what could (at some point during processing) make this file inaccessible? The issue persists after leaving the server alone for a bit - a subsequent call 4 minutes later also fails. Stopping and restarting the server resolves it. The calls are coming in from the test program at a rate of about 10 per second.

Is there maybe a way to load the ".se1" files into server memory, so it doesn't need to keep accessing them on the drive? Looks like it's only about 4 megs for all the data I could want. (13th through 24th centuries.)

**Comment by apollograce** [comment]
With further testing, I find that after restarting the server, it consistently fails at iteration 1363, which in our case is after 2726 sets of data (and particularly 2726 calls to get Chiron). This is consistently the date 1959-07-18T06:46:13Z / JD 2436767.78210... But there's nothing wrong with that date. When I restart the server and run that date directly, no issue - and if I run a few unrelated tests, and then do the iterated test, it fails earlier, with different data, at iteration 1359. So it definitely seems to be about how many times I'm hitting this thing, rather than a particular date.

**Comment by astrorigin** [comment]
Without access to your system and software, I cannot look further into it. Check that you correctly call set_ephe_path() and maybe set the environment variable SE_EPHE_PATH too.
I'm sorry that I am not in a position to help you as many other problems can arise in a server setting like yours. Keep us updated on your situation...

**Comment by astrorigin** [comment]
One year later...
