### ISSUE TITLE
Possible star rise_transit bug

### ISSUE THREAD

**Issue by crv-intel** [astrorigin/pyswisseph#38]
The following code:

#!/usr/bin/env python3

import math
import swisseph as swe

def julian2date(jd):

   ret = swe.revjul(jd, swe.GREG_CAL)
   h = int(math.floor(ret[3]))
   m = int(math.floor(math.fmod(ret[3] * 60, 60)))
   s = int(math.floor(math.fmod(ret[3] * 3600, 60)))
   t = "%04d-%02d-%02d_%02d:%02d:%02d" % (ret[0], ret[1], ret[2], h, m, s)
   return t

swe.set_ephe_path("/home/chris/swe")
year = 2020
month = 12
day = 20
hour = 0
jd_search = swe.julday(year, month, day, hour, swe.GREG_CAL)
ret = swe.rise_trans(jd_search, "Sirius", 0, 52, 100, 1024, 15,
                     swe.CALC_RISE | swe.BIT_DISC_CENTER)
print("Rise: ", julian2date(ret[1][0]))
ret = swe.rise_trans(jd_search, "Sirius", 0, 52, 100, 1024, 15,
                     swe.CALC_MTRANSIT | swe.BIT_DISC_CENTER)
print("Transit: ", julian2date(ret[1][0]))
ret = swe.rise_trans(jd_search, "Sirius", 0, 52, 100, 1024, 15,
                     swe.CALC_SET | swe.BIT_DISC_CENTER)
print("Set: ", julian2date(ret[1][0]))
ret = swe.rise_trans(jd_search, "Sirius", 0, 52, 100, 1024, 15,
                     swe.CALC_ITRANSIT | swe.BIT_DISC_CENTER)
print("I transit: ", julian2date(ret[1][0]))
swe.close()

Produces the folowing: 

Rise:  2020-12-20_08:07:43
Transit:  2020-12-20_00:49:47
Set:  2020-12-20_15:47:51
I transit:  2020-12-20_12:47:49

My other ephemeris software gives the rise, transit, set, and itransit times for Sirius as follows:

Rise: 20:18
Transit: 00:50
Set: 05:19
I transit: 12:48

My code above, before the upgrade to the current release, gave the correct values. Has a bug been introduced in the current release, or has there been some parameter change that I am not aware of. If I use similar code to compute planetary RSTI's they give the correct values.

Thank you

Chris

**Comment by astrorigin** [comment]
Any more details?

It could be that a change in the Swiss Ephemeris has broken your code, as we did not introduce changes ourselves.

What other software are you using for comparison?

I suggest that you try again with the current development release (master branch) of this repository.

**Comment by crv-intel** [comment]
Thanks for your reply. I can confirm that building the current development master release as you suggested fixed the bug I reported above. The code that I originally posted above produces the following result:

Rise:  2020-12-20_20:13:03
Transit:  2020-12-20_00:49:47
Set:  2020-12-20_05:22:35
I transit:  2020-12-20_12:47:49

Which is close to the other Ephemeris software (Star Charts) that I use.

Thank you.
