### ISSUE TITLE
i get stuck when using function swe._next_aspect2

### ISSUE THREAD

**Issue by trangtv57** [astrorigin/pyswisseph#42]
Hi,
I have used function swe._next_aspect2 for getting time for occurred apsect between 2 planet, but sometime i get stuck when using this function like:
```
current_day = swe.julday(2021, 1, 21, 0)

planet = 2 #mecury
planet_position_birth = 228.09
aspect = 60  # if i use aspect = 60.0, function work well and everything run so fast.
output_aspect = swe._next_aspect2(planet, aspect, planet_position_birth, current_day))
aspect = 90 # this function get stuck, don't return and still runing so a long time and maybe like infinity  loop.
output_aspect = swe._next_aspect2(planet, aspect, planet_position_birth, current_day))

```
Can you check then tell me what's a problem and how to fix it ?  thanks.

**Comment by astrorigin** [comment]
You fix it by using the latest version of the software. Best taken from here directly.

**Comment by trangtv57** [comment]
thanks @astrorigin 
can you check what's latest version of  pyswisseph, i clone this repo, and install direction by pip install -e ., It's take version 2.8.0.post1. But problem still exist?
So i want you can confirm what's version is latest or another branch should be checkout. 
Thanks you

**Comment by trangtv57** [comment]
sorry @astrorigin , when i clear all cache and install again, it's show version: 2.8.0.post2. But when i run this code above. It's show AttributeError: module 'swisseph' has no attribute '_next_aspect2'. And i looking in file pyswisseph, and it's extractly not have this function. :((

**Comment by astrorigin** [comment]
Namespace changed. You clone the repo (with submodules), and use something like:
`from swisseph import contrib as swh
swh.next_aspect2(...)`

**Comment by trangtv57** [comment]
tks @astrorigin. I have run success my code, but seem your code not fast as old version when have bug. Does it right?

**Comment by astrorigin** [comment]
Can you explain? What is not right? How fast exactly?

**Comment by trangtv57** [comment]
sorry @astrorigin , i try to test get list aspect of current planet with natural planet [0, 60, 90, 120, 180], but some planet like pluto, uranus, neptune ... need time so long for find aspect like:
```
current day: 2021-6-20
born_location = "ha noi, viet nam"
born_time = "1994-11-22 22:00"
with function  swh.next_aspect2(pluto_id, e_aspect, pos_birth, current_day) and e_aspect in l_aspect:
i have output: planet: Pl make aspect 0.0 with Su at (2241, 12, 20, 9, 44, 29)
planet: Pl make aspect 60.0 with Su at (2023, 3, 28, 4, 12, 35)
planet: Pl make aspect 90.0 with Su at (2043, 3, 11, 23, 40, 3)
planet: Pl make aspect 120.0 with Su at (2067, 4, 12, 6, 9, 17)
planet: Pl make aspect 180.0 with Su at (2127, 6, 19, 19, 10, 19)
```
And because 2241 or 2067 may be so long, i don't need search aspect like this. It's make function take so long time.
In the older version, i remember next_aspect function have time_step, and time_span for search in duration of time, how can i use it in latest version for control search near time current. If don't have aspect in time return none or something like this.
Tks.

**Comment by astrorigin** [comment]
See [https://astrorigin.com/pyswisseph/pydoc/swisseph.contrib.html](https://astrorigin.com/pyswisseph/pydoc/swisseph.contrib.html)
