### ISSUE TITLE
Error On Make HTML

### ISSUE THREAD

**Issue by pije76** [astrorigin/pyswisseph#45]
Firstly thank you to make this library in Python.
When I buld a doc, I got: `AttributeError: module 'swisseph' has no attribute 'solcross'`

**Comment by astrorigin** [comment]
Can you verify which version is being used? `print(swisseph.version, swisseph.__version__)`

The library being used is an older version not including `solcross`. Try removing all previously installated `swisseph` module from your `sys.path`. Recompile from GitHub source (or install from PyPI prerelease channel with `pip install -U --pre pyswisseph`). Documentation is also found on the website.
