### ISSUE TITLE
Speed of House Cusps

### ISSUE THREAD

**Issue by imanewman** [astrorigin/pyswisseph#46]
Hello, first I would like to thank you for the usefulness of this package so far, I've very grateful.

I recently noticed that there is no equivalent to the `swe_houses_ex2()` function within the Swiss ephemeris itself. This function is super useful in that it calculates the speed of the house cusps, which I currently need for what I'm making.

The original function can be found in the API docs under the section:
[15.4. swe_houses_ex() and swe_houses_ex2()](https://www.astro.com/swisseph/swephprg.htm#_Toc78973553)

I was wondering if there is any way this function can be added to this library? Since `swe_houses_ex()` already exists as `houses_ex()`, I was hoping it wouldn't be a huge lift to also include.

**Comment by astrorigin** [comment]
That function exists in the current pre-release version which you can get with `pip install -U --pre pyswisseph`.

```
Help on built-in function houses_ex2 in swisseph:

swisseph.houses_ex2 = houses_ex2(...)
    Calculate houses cusps and cusps speeds (UT).
    
    :Args: float tjdut, float lat, float lon, bytes hsys=b'P', int flags=0
    
     - tjdut: input time, Julian day number, Universal Time
     - lat: geographic latitude, in degrees (northern positive)
     - lon: geographic longitude, in degrees (eastern positive)
     - hsys: house method identifier (1 byte)
     - flags: ephemeris flag, etc
    
    :Return: (cusps), (ascmc), (cuspsspeed), (ascmcspeed)
    
     - cusps: tuple of 12 float for cusps (except Gauquelin: 36 float)
     - ascmc: tuple of 8 float for additional points
     - cuspsspeed: tuple of 12 float for cusps speeds
     - ascmcspeed: tuple of 8 float for speeds of additional points
    
    This function raises swisseph.Error in case of fatal error.
```

**Comment by imanewman** [comment]
Thank you!

**Comment by imanewman** [comment]
This pre-release version, `pyswisseph-2.10.2.0.dev1` seems to break the `cotrans()` function by editing the call signature to only two arguments instead of the original 4. Do you have an idea of what could be wrong here?

**Comment by imanewman** [comment]
Ah never mind, I see that the call signature has been changed to a tuple for the first 3 after looking into the code.

**Comment by astrorigin** [comment]
Yes, a number of functions have changed, sometimes in an attempt to make them more similar to the C API.
Some more changes are to be expected...
Thanks
