### ISSUE TITLE
Missing releases on PyPi

### ISSUE THREAD

**Issue by szedjani** [astrorigin/pyswisseph#47]
Hi, I've built a tool for a friend in the past, but now when I wanted to continue the development I noticed that I cannot install the specific version from PyPi, because only the latest release is available and even that release has breaking changes. Could you please keep the version history on PyPi? Thanks.

**Comment by astrorigin** [comment]
Sorry: oldest releases were removed from PyPI and are gone for good (too many bugs). You are invited to use the latest release or better, pre-release stuff from PyPI (see documentation).
