### ISSUE TITLE
PySwisseph 2.8.0  swe constants

### ISSUE THREAD

**Issue by naturalstupid** [astrorigin/pyswisseph#49]
After switching from 2.05 to 2.8.0, I get the following error:
AttributeError: module 'swisseph' has no attribute 'RAHU'
But when I type swe. I Can see RAHU being there.
anyway I after setting this manually to swe.RAHU = 10, then I get similar constant errors for SURYA, KUJA all Indian Planet names.
I had to rename them as swe.SURYA = swe.SUN etc
Switching back to 2.05 my python script works fine (without having to rename the constants)

**Comment by astrorigin** [comment]
Those constants are not part of the Swiss Ephemeris and moved to submodule `swisseph.contrib`.
