### ISSUE TITLE
Function not working swe.set_ephe_path

### ISSUE THREAD

**Issue by damirmur** [astrorigin/pyswisseph#53]
print(swe.EPHE_PATH)
.:/users/ephe2/:/users/ephe/

swe.set_ephe_path('swiss/ephe')
print(swe.EPHE_PATH)
.:/users/ephe2/:/users/ephe/

swe.EPHE_PATH='swiss/ephe'
print(swe.EPHE_PATH)
swiss/ephe

**Comment by astrorigin** [comment]
The swe.EPHE_PATH variable is read-only and probably has no other use than internally at astro.com . Please read the manual.
