### ISSUE TITLE
Planetary moons position, the ephemeris file choose?

### ISSUE THREAD

**Issue by yinzhq** [astrorigin/pyswisseph#68]
Dear All,
my python pyswisseph package version is 2.10.3, 
I try to use this package to calculate the position of planetary moons.
I download the ephemeris form dropbox.

when I run the follow lines:
################################
swe.set_ephe_path('/Users/mac/sweph/ephe') 
cjd = swe.julday(2023, 1, 1, 0.0)
flags = swe.FLG_EQUATORIAL | swe.FLG_SWIEPH | swe.FLG_SPEED 
plm = swe.calc_ut(cjd, swe.PLMOON_OFFSET+501, flags)
################################

the error is :"Error: swisseph.calc_ut: SwissEph file 'sepm9501.se1' not found in PATH '/Users/mac/sweph/ephe/'"
in the dropbox folder 'ephe',  I think there are  'semo_18.se1' file shoul be used in the case. 
I can not find like 'sepm9501.se1' files in the dropbox.

could you kindly to tell me, what kind of problems in my case.
did I use the wrong sentence ? or set a wrong path? or other things?   

Thanks a lot!

**Comment by astrorigin** [comment]
According to documentation, those files must be found in the subfolder `ast`.

**Comment by astrorigin** [comment]
Now that they fixed their messy dropbox, we can close. Thank you.
