### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by d3cxxxx** [astrorigin/pyswisseph#78]
Is there a plan to upgrade this library to support python 3.12 and also support aarch64 (arm-64 bit) platform (for linux instead of macos)?

Trying to run this as a lambda function on arm but facing a lot of issues. If this can be done using source code, please guide me on the requirements/process.

**Comment by d3cxxxx** [comment]
Was an error in my env. This does compile fine on x86_64 linux. Will open a separate issue if needed.

**Comment by mukul-data** [comment]
@d3cxxxx  I am facing similar error, could you throw some light on how were you able it to compile it for lambda
