### ISSUE TITLE
Windows installation BUG ?

### ISSUE THREAD

**Issue by androidanit** [astrorigin/pyswisseph#9]
Astrorigin,

While installing pyswisseph on windows + python27; encountered a BUG which caused the error.

Steps followed.
1. Installed VC++ compiler for python 2.7 Link : http://aka.ms/vcpython27
2. Then fired - pip install pyswisseph It ran into errors ! The referenced lines were from swephelp\swhgeo.c pointing to codeblock which is not meant for WIN32. That is - 
   #ifndef WIN32 
     char *saveptr; 
     ptr = strtok_r(buf, ":", &saveptr); 
   #else 
     ptr = strtok(buf, ":");
3. So applied quick and dirty patch in swephelp\swhgeo.c - 
   #ifndef WIN32 
   #define WIN32 1 
   #endif /\* Hey I am WIN32 */
4. Then installed from source pip install <Path to local copy of pyswisseph >
5. It worked!!!

I am not expert, so could get to root cause.
If you can confirm and fix this BUG, it will save days for windows users :-)

Thanks

**Comment by astrorigin** [comment]
That should be fixed now.
